INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Jon', 'Snow');
INSERT INTO ADDRESS(ADDRESS_ID, ADDRESS_DETAILS, CUSTOMER_ID) VALUES(1, 'Winterfell', 1);
INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Oberyn', 'Martell');
INSERT INTO ADDRESS(ADDRESS_ID, ADDRESS_DETAILS, CUSTOMER_ID) VALUES(2, 'Dorne', 2);